In [16]:
import pandas as pd

In [5]:
df = pd.read_csv('/content/drive/MyDrive/Machine Learning/Fake News Classifier/train.csv')
df.tail()

id  ... label
20795  20795  ...     0
20796  20796  ...     0
20797  20797  ...     0
20798  20798  ...     1
20799  20799  ...     1

[5 rows x 5 columns]

In [6]:
df = df.dropna()

In [7]:
x = df.drop('label', axis=1)
x.head()

id  ...                                               text
0   0  ...  House Dem Aide: We Didn’t Even See Comey’s Let...
1   1  ...  Ever get the feeling your life circles the rou...
2   2  ...  Why the Truth Might Get You Fired October 29, ...
3   3  ...  Videos 15 Civilians Killed In Single US Airstr...
4   4  ...  Print \nAn Iranian woman has been sentenced to...

[5 rows x 4 columns]

In [8]:
x.shape

(18285, 4)

In [9]:
y = df['label']
y.shape

(18285,)

In [10]:
import tensorflow as tf
tf.__version__

'2.5.0'

In [11]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM,Dense

In [12]:
voc_size = 5000

In [13]:
messages = x.copy()
messages.reset_index(inplace=True)

In [14]:
import nltk
import re
from nltk.corpus import stopwords

In [15]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [17]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus=[]
for i in range(0, len(messages)):
  print(i)
  review = re.sub('[^a-zA-Z]',' ', messages['title'][i])
  review= review.lower()
  review = review.split()
  review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)


Streaming output truncated to the last 5000 lines.
13285
13286
13287
13288
13289
13290
13291
13292
13293
13294
13295
13296
13297
13298
13299
13300
13301
13302
13303
13304
13305
13306
13307
13308
13309
13310
13311
13312
13313
13314
13315
13316
13317
13318
13319
13320
13321
13322
13323
13324
13325
13326
13327
13328
13329
13330
13331
13332
13333
13334
13335
13336
13337
13338
13339
13340
13341
13342
13343
13344
13345
13346
13347
13348
13349
13350
13351
13352
13353
13354
13355
13356
13357
13358
13359
13360
13361
13362
13363
13364
13365
13366
13367
13368
13369
13370
13371
13372
13373
13374
13375
13376
13377
13378
13379
13380
13381
13382
13383
13384
13385
13386
13387
13388
13389
13390
13391
13392
13393
13394
13395
13396
13397
13398
13399
13400
13401
13402
13403
13404
13405
13406
13407
13408
13409
13410
13411
13412
13413
13414
13415
13416
13417
13418
13419
13420
13421
13422
13423
13424
13425
13426
13427
13428
13429
13430
13431
13432
13433
13434
13435
13436
13437
13438
13439
13440
13441
13442
1

In [18]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [19]:
one_hot_rep = [one_hot(word,voc_size) for word in corpus]
one_hot_rep

[[1743, 2864, 4205, 2418, 2515, 4879, 1287, 3407, 1241, 1888],
 [2051, 2970, 474, 1535, 3059, 3854, 3907],
 [1556, 4943, 168, 1117],
 [754, 1471, 1477, 2801, 1344, 3891],
 [3416, 3059, 3426, 272, 3779, 639, 3059, 1621, 4440, 2578],
 [3874,
  1652,
  659,
  3591,
  2012,
  2347,
  3916,
  4690,
  3695,
  3975,
  3173,
  3246,
  4917,
  3671,
  3907],
 [2011, 1137, 3241, 901, 3426, 2519, 3717, 1544, 813, 3241, 3862],
 [1712, 4920, 4786, 3212, 4936, 1244, 2347, 2278, 813, 3241, 3862],
 [1773, 1381, 1289, 4773, 1958, 382, 4688, 1381, 2347, 3542],
 [1216, 10, 4309, 4118, 660, 1878, 2978, 2892],
 [2891, 2483, 3905, 797, 1686, 4168, 3502, 4841, 1531, 3500, 2505],
 [2801, 2250, 2515, 382, 2347, 4936],
 [4752, 2286, 1825, 1162, 4451, 1308, 2366, 4689, 497],
 [659, 579, 3111, 4962, 901, 2283, 1957, 813, 3241, 3862],
 [2032, 1367, 2346, 4388, 4032, 813, 3241, 3862],
 [2415, 155, 4784, 2488, 4200, 975, 935, 1761, 564, 3727],
 [1753, 393, 2970],
 [3595, 1218, 4502, 4162, 2347, 4460, 2460, 3907],
 [

In [20]:
sent_length = 20
embedded_docs = pad_sequences(one_hot_rep, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 3407 1241 1888]
 [   0    0    0 ... 3059 3854 3907]
 [   0    0    0 ... 4943  168 1117]
 ...
 [   0    0    0 ...  813 3241 3862]
 [   0    0    0 ...  365 4204 3791]
 [   0    0    0 ...   41 4636  687]]


In [21]:
len(embedded_docs)

18285

In [22]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 1743,
       2864, 4205, 2418, 2515, 4879, 1287, 3407, 1241, 1888], dtype=int32)

In [24]:
embedding_vector_feature = 40
model= Sequential()
model.add(Embedding(voc_size, embedding_vector_feature, input_length = sent_length))
model.add(LSTM(100))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 20, 40)            200000    
_________________________________________________________________
lstm (LSTM)                  (None, 100)               56400     
_________________________________________________________________
dense (Dense)                (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [25]:
import numpy as np
x_final = np.array(embedded_docs)
y_final = np.array(y)

In [26]:
x_final.shape, y_final.shape

((18285, 20), (18285,))

In [30]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x_final, y_final, test_size= 0.33, random_state=42)

In [31]:
x_train.shape

(12250, 20)

In [32]:
model.fit(x_train,y_train, validation_data=(x_test,y_test), epochs = 10, batch_size= 64)

Epoch 1/10
192/192 [==============================] - 10s 38ms/step - loss: 0.3545 - accuracy: 0.8227 - val_loss: 0.2080 - val_accuracy: 0.9107
Epoch 2/10
192/192 [==============================] - 7s 35ms/step - loss: 0.1464 - accuracy: 0.9419 - val_loss: 0.2083 - val_accuracy: 0.9181
Epoch 3/10
192/192 [==============================] - 7s 35ms/step - loss: 0.0989 - accuracy: 0.9622 - val_loss: 0.2235 - val_accuracy: 0.9074
Epoch 4/10
192/192 [==============================] - 7s 35ms/step - loss: 0.0659 - accuracy: 0.9766 - val_loss: 0.2702 - val_accuracy: 0.9171
Epoch 5/10
192/192 [==============================] - 7s 35ms/step - loss: 0.0420 - accuracy: 0.9847 - val_loss: 0.3685 - val_accuracy: 0.9160
Epoch 6/10
192/192 [==============================] - 7s 35ms/step - loss: 0.0230 - accuracy: 0.9927 - val_loss: 0.3810 - val_accuracy: 0.9102
Epoch 7/10
192/192 [==============================] - 7s 35ms/step - loss: 0.0185 - accuracy: 0.9944 - val_loss: 0.4499 - val_accuracy: 0.897

In [33]:
y_pred = model.predict_classes(x_test)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [35]:
from sklearn.metrics import confusion_matrix

In [36]:
confusion_matrix(y_test,y_pred)

array([[3074,  345],
       [ 193, 2423]])

In [37]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9108533554266777